// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyiyydakxqpygstaxqfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5aXl5ZGFreHFweWdzdGF4cWZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDY2NzksImV4cCI6MjA2ODU4MjY3OX0.qJbean6B1IF4YWWCbQub0547f66zStUdC8EAEb3tWi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});